//
// Created by Sidharth Gurbani on 12/1/20.
//

#ifndef PAGE_REPLACEMENT_SIMULATOR_PAGE_REPLACEMENT_ALGORITHM_H
#define PAGE_REPLACEMENT_SIMULATOR_PAGE_REPLACEMENT_ALGORITHM_H
int GetPageToReplace();
#endif //PAGE_REPLACEMENT_SIMULATOR_PAGE_REPLACEMENT_ALGORITHM_H
